name: CMS CI

on: [push, pull_request]

env:
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/745e923a-3f85-4e1e-b6dd-637c0e9ccba6/w_HPCKit_p_2024.2.1.80_offline.exe
  WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler

jobs:
  build:
    runs-on: [windows-2019]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # # Setup Visual Studio
      # - name: Setup Visual Studio
      #   uses: seanmiddleditch/gha-setup-vsdevenv@master

      # # Setup Dev Cmd
      # - name: Setup Dev Cmd
      #   uses: ilammy/msvc-dev-cmd@v1

      # Setup Intel HPC Kit
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel-classic

      # Use the cmake action
      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
        with:
          source-dir: source

      # # Build the code
      # - name: MSBuild
      #   run: |
      #     cd Intel_vs2019
      #     devenv CMS2D_V5.3.sln /Build

      # List directory contents
      - name: List directory
        run: |
          cd Intel_vs2019
          dir
          type UpgradeLog.htm
