name: CMS CI

on: [push, pull_request]

env:
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/745e923a-3f85-4e1e-b6dd-637c0e9ccba6/w_HPCKit_p_2024.2.1.80_offline.exe
  WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler

jobs:
  build:
    runs-on: [windows-2019]
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install windows dependencies
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: install
        run: ci-scripts/install_windows.bat $WINDOWS_HPCKIT_URL $WINDOWS_FORTRAN_COMPONENTS

      # Build the code
      - name: MSBuild
        run: |
          - cd Intel_vs2019 
          - msbuild CMS2D_V5.3.sln

      # List directory contents
      - name: List directory
        run: ls -lah
